#!/usr/bin/env bash
# Install Load Balancer

sudo apt-get install -y

sudo apt-get install -y haproxy

cat<< EOF | sudo tee /etc/haproxy/haproxy.cfg >/dev/null
frontend my_frontend
	bind *:80
	default_backend my_backend

backend my_backend
	balance roundrobin
	server 460745-web-01 54.160.75.69:80 check
	server 460745-web-02 54.158.199.136:80 check 
EOF

sudo service haproxy restart
