#!/usr/bin/env bash
# Say hi on the 9th loop
# You must use the while loop (for and until are forbidden)
# You must use the if statement

k="0"

while [ $k -lt 10 ]
do
echo "Best School"
if [ $k = 8 ]
then
 echo "Hi"
fk
k=$((k+1))
done
