#!/usr/bin/env bash
# Print bad luck at specifi index.
# You must use the while loop (for and until are forbidden)
# You must use the if, elif and else statements
i=1

while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
