#!/usr/bin/env bash
# This script loops from 1 to 20 displaying
# You must use the while loop (for and until are forbidden)
# You must use the case statement

i="1"

while [ $i -lt 21 ]
do
case $i in
4)
	echo "$i"
	echo "bad luck from China"
	;;
9)
	echo "$i"
	echo "bad luck from Japan"
	;;
17)
	echo "$i"
	echo "bad luck from Italy"
	;;
*)
	echo "$i"
	;;
esac
i=$((i+1))
done
